### ISSUE TITLE
how to add jquery?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [RD17/react-trumbowyg#6]
I'm very new to react. In your instructions you say to add this code:

```
new webpack.ProvidePlugin({
    $: "jquery",
    jQuery: "jquery"
}) 
```

In what file do I insert that code?

Thanks

**Comment by sochix** [comment]
In webpack config file. Check it here https://github.com/RD17/react-trumbowyg/blob/master/examples-es6/webpack.config.js
