### ISSUE TITLE
How to change the language of the editor?

### ISSUE THREAD

**Issue by franlopezm** [RD17/react-trumbowyg#9]
I have read the documentation, but I have not seen how to change the language, for props.

**Comment by Alex-D** [comment]
Hi!

Note: I'm the Trumbowyg maintainer, not the react-trumbowyg one ^^

I've created a PR here with the fix: https://github.com/RD17/react-trumbowyg/pull/10 (not tested)

**Comment by sochix** [comment]
Merged, thanks @Alex-D !

**Comment by Pericatibio** [comment]
Buenos días, soy nuevo por aquí, estoy intentando cambiar el idioma de trumbowyg de ingles a español, he leído las indicaciones del desarrollador pero no se muy bien como ni donde incluir las modificaciones, he probado varias veces sin éxito, por favor alguien puede ampliarme la información para cambiar el idioma y como hacerlo, GRACIAS.
